### ISSUE TITLE
Release CppUTest 3.9?

### ISSUE THREAD

**Issue by Andne** [cpputest/cpputest#1061]
We still have a few open pull requests, about half of which are marked as in error, but are we getting to a point where CppUTest 3.9 should be released?

Maybe this issue can become the tracking list for what needs to be done before the release.  I've started with my list of things I think would be quick to clean up first:

- [x] #954 FENV Test Failures under Visual Studio 2013/2015 - I think this has been corrected, once I remember what the original issue was
- [ ] #916 Compiler warning Visual Studio 2005 & 2013 - I think the warning is fixed, there was an open question about CRLF that got dropped
- [ ] #914 Fix line endings - There was a pull request at one point, so likely these have been (mostly) fixed
- [ ] #350 Fix .gitattributes - There's a comment about needing to agree on the fix here.
- [ ] #115 Resolve the library directory thing - I vaguely remember some recent commits/comments that may have done this

Other thoughts/needs?

**Comment by basvodde** [comment]
Ok. Sorry for my limited attention to this so far. It should get better again at some point.

**Comment by wiredsource** [comment]
Hi guys

I'm looking forward to this upcoming release. Atm. i'm running 3.8 on win32 and iar which seems to go pretty well. Although at some point i tried copying/overwriting the files(3.8) with master and the whole framework crashed in the SimpleString.cpp file (looked like a overflow).
I'm running CppCheck as part of my CI on jenkins and found a few places were there might could be an issue. 
Perhaps CppCheck could come in handy but you properly already use/know it...?
BR
W

**Comment by Andne** [comment]
@basvodde What are your thoughts on this?  I know I opened it a while ago and haven't done much myself either.  Looking though the above PR's, it seems that most are likely fixed but the loop just wasn't closed.  Do you want to just close them or do we need to get the person that reported the issue to say yes, they're good?

Are there any more recent things that should be included before another release?

**Comment by basvodde** [comment]
My thought is still the same. Hope to have some bandwidth to check this in the future :(

**Comment by jwgrenning** [comment]
I'd like to suggest

1) changing the configure/make to support users of MakefileWorker.mk
2) Adding an example without MakefileWorker.mk

Right now the examples directory does not build out of the box.



--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
Cell: +1 847-630-0998
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by basvodde** [comment]
Releasing 4.0 soon.
